zip parser bugfix
when extracting a zip file, zip_extract_handler function's return value and the lines processing it do not match in terms of attribute names, thus giving the following error


  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/llmware/parsers.py", line 330, in _collator
    pdf_found += zip_work_order["pdf_found"]
KeyError: 'pdf_found'